
# De qual imagem já existente minha imagem irá derivar
FROM eclipse-temurin:25-jdk-alpine

# Porta que será exposta ao host
EXPOSE 8000

# Qual será o diretório inicial ao entrar na imagem
WORKDIR /app

# Edição do comando padrão ao construir a imagem
CMD [ "jwebserver", "-b", "0.0.0.0"]

