/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import module java.base;

public class App {

    public static void main(String[] args) {

        int port = 1234;

        IO.println("..:: SERVER ::..");

        try (ServerSocket serverSocket = new ServerSocket(port)){
            IO.println("Waiting for connections...");

            while(!Thread.currentThread().isInterrupted()){
                Socket clientSocket = serverSocket.accept(); // Waiting IO
                Thread.ofVirtual().start(new AssistClient(clientSocket));
            }

        } catch (Exception e) {
            System.err.println("Error to create the socket");
        }
    }
}
