/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import module java.base;

public class App {

    public static void main(String[] args) {

//      Declaration of the port that we'll use
        int port = 1234;

        IO.println("..:: SERVER ::..");

        try (ServerSocket serverSocket = new ServerSocket(port)){
            IO.println("Waiting for connections...");

            Socket clientSocket = serverSocket.accept();

            var clientAddress = clientSocket.getInetAddress().getHostAddress();
            var clientPort = clientSocket.getPort();

            System.out.printf("Client connected: %s:%d%n", clientAddress, clientPort);


//          Here we are realizing the establishment of the IO flow
            var reader = new BufferedReader(
                    new InputStreamReader(clientSocket.getInputStream(), StandardCharsets.UTF_8)
            );

            var writer = new BufferedWriter(
                    new OutputStreamWriter(clientSocket.getOutputStream(), StandardCharsets.UTF_8)
            );

//          Communication Protocol
            String message = "";

            while(!message.toLowerCase().equals("sair")){
                message = reader.readLine();

                System.out.printf("[%s:%d] -> %s\n", clientAddress, clientPort, message);

                writer.write(message.toUpperCase());
                writer.newLine();
                writer.flush();
            }

            IO.println("End server!");
            reader.close();
            writer.close();

        } catch (Exception e) {
            System.err.println("Error to create the socket");
        }

    }
}