services:
  redis:
    image: redis:alpine
    networks:
      - rede1
  

  webapp:
    build: .
    ports:
      - 5000
    volumes:
      - ./app:/app
    
    deploy:
      replicas: 3
    networks:
      - rede1
      - rede2
    
  caddy:
    image: caddy:alpine
    ports: 
      - 4000:4000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - rede2

networks:
  rede1:
  rede2: