/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import module java.base;

public class App{

    public static void main(String[] args) {

        String serverAddress = "localhost";
        int serverPort = 1234;

        String fileName = "/home/aluno/Engenharia-de-Telecomunicacoes/6th-semester/STD/1st-Test/LAB02/std-lab-sockets.pdf";
        try (var socket = new Socket(serverAddress, serverPort);
             var dos = new DataOutputStream(socket.getOutputStream());
             var dis = new DataInputStream(socket.getInputStream())) {

            // Send the file name wanted
            dos.writeUTF(fileName);
            dos.flush();

            // Show the path to save the file received
            Path destiny = Path.of(fileName);

            // Read the server answer (file length or -1 to indicate error)
            long length = dis.readLong();

            if (length > 0) {
            // Will save the received file in the specified path, replacing if already exist.
                long bytesReceived = Files.copy(dis, destiny, StandardCopyOption.REPLACE_EXISTING);
                System.out.printf("File saved: %s (%d / %d bytes)%n",
                        fileName, bytesReceived, length);
            } else {
                System.out.println("The server said that file doesn't exist. " + fileName);
            }
        } catch (Exception e){
            System.err.println("Erro: " + e);
        }
    }
}
