/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import io.grpc.Server;
import io.grpc.ServerBuilder;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("Iniciando o servidor");
// Padrão de projeto Builder.
// Veja mais em https://java-design-patterns.com/patterns/builder/
// Iniciando o servidor com a implementação da AgendaImpl
        Server servidor = ServerBuilder.forPort(50051)
                .addService(new ScheduleImpl())
                .build()
                .start();
// Para finalizar o servidor quando a JVM for finalizada
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("servidor gRPC sendo desligado pois a JVM está sendo desligada");
            servidor.shutdown();
            System.out.println("Servidor parado com sucesso");
        }));
// Para Finalizar o servidor
        servidor.awaitTermination();
    }
}
